/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfacez;

/**
 *
 * @author joska
 */
public class InicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_imagen_almacen = new javax.swing.JLabel();
        panel_inicio_sesion = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tf_usuario = new javax.swing.JTextField();
        usuario = new javax.swing.JLabel();
        lb_contrasenia = new javax.swing.JLabel();
        bt_iniciar_sesion = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setMaximumSize(new java.awt.Dimension(900, 550));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setMaximumSize(new java.awt.Dimension(900, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 500));
        jPanel1.setLayout(null);

        lb_imagen_almacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesLogin/bodega.png"))); // NOI18N
        jPanel1.add(lb_imagen_almacen);
        lb_imagen_almacen.setBounds(0, 0, 450, 500);

        panel_inicio_sesion.setBackground(new java.awt.Color(255, 255, 255));
        panel_inicio_sesion.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesLogin/Titulo.png"))); // NOI18N
        panel_inicio_sesion.add(jLabel2);
        jLabel2.setBounds(0, -20, 400, 80);

        tf_usuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tf_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_usuarioActionPerformed(evt);
            }
        });
        panel_inicio_sesion.add(tf_usuario);
        tf_usuario.setBounds(30, 120, 340, 40);

        usuario.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        usuario.setText("Usuario:");
        panel_inicio_sesion.add(usuario);
        usuario.setBounds(150, 90, 110, 30);

        lb_contrasenia.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        lb_contrasenia.setText("Contraseña:");
        panel_inicio_sesion.add(lb_contrasenia);
        lb_contrasenia.setBounds(120, 200, 170, 30);

        bt_iniciar_sesion.setFont(new java.awt.Font("Arial Narrow", 2, 18)); // NOI18N
        bt_iniciar_sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesLogin/Boton.png"))); // NOI18N
        bt_iniciar_sesion.setBorder(null);
        bt_iniciar_sesion.setBorderPainted(false);
        bt_iniciar_sesion.setContentAreaFilled(false);
        bt_iniciar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_iniciar_sesionActionPerformed(evt);
            }
        });
        panel_inicio_sesion.add(bt_iniciar_sesion);
        bt_iniciar_sesion.setBounds(20, 310, 360, 50);
        panel_inicio_sesion.add(jPasswordField1);
        jPasswordField1.setBounds(39, 241, 330, 40);

        jPanel1.add(panel_inicio_sesion);
        panel_inicio_sesion.setBounds(480, 40, 400, 420);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_usuarioActionPerformed

    private void bt_iniciar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_iniciar_sesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_iniciar_sesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_iniciar_sesion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel lb_contrasenia;
    private javax.swing.JLabel lb_imagen_almacen;
    private javax.swing.JPanel panel_inicio_sesion;
    private javax.swing.JTextField tf_usuario;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
